# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bfa85e18267ea9a3517899bc82021c49fd507c331803d8a3c059983d7a50d5206e321e84d8ec9497d6d66c0311d5846d2ad422c7c3ad6c9d904784770a94231b

test:
  secret_key_base: 9e4b91e83d87c9a13900f518e4b8b400af41bdc7ff2aadea75085cd72fdbfeaff8286fdc4935395f42cb826b2e5129a110d837be4b3654320ed4f0afbea180d0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
